# Generated by Django 5.2.2 on 2025-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='pending', max_length=10),
        ),
    ]
