# Generated by Django 5.2.2 on 2025-08-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
